renovate.json
Closes #<issue number here>.
Backstage has its own upgrade mechanism that we will use to update its dependencies etc. along with required manual work.
For now we'll let React stay aligned with that.
Added package rule to renovatebot configuration to ignore these packages.
---
=> chore: Ignore backstage and react packages in renovate

plugins/codebuild/backend/src/index.ts, plugins/codebuild/backend/src/plugin.ts, plugins/codepipeline/backend/src/index.ts, plugins/ecs/backend/src/index.ts
To make these plugins work with the new Backstage backend system
Export plugin as default from index.ts
No need
---
=> fix: export plugins as default for new backstage backend

plugins/codebuild/backend/src/plugin.ts, plugins/codepipeline/backend/src/plugin.ts, plugins/ecs/backend/src/plugin.ts
Closes #<issue number here>.
New authentication changes to Backstage mean that health check endpoint is inaccessible without auth policy change to allow unauthenticated access.
Added unauthenticated auth policy for health check path in each plugin backend:
```typescript
httpRouter.addAuthPolicy({
path: '/health',
allow: 'unauthenticated',
});
```
Local testing
---
=> feat: Added auth policy for health check endpoints

plugins/core/scaffolder-actions/package.json, plugins/core/scaffolder-actions/src/actions/s3/cp.test.ts, plugins/core/scaffolder-actions/src/actions/s3/cp.ts, yarn.lock
N/A
The S3 cp action should use the `path` option as provided instead of adding wildcards to it.
Pass through path option directly
Added unit tests for this and other scenarios.
---
=> fix: S3 cp action should use path as provided

plugins/core/common/src/locator/resource-locator-factory.ts
Closes #<issue number here>.
The resource locator type configuration option was intended to be optional, but the lookup using the config API treats it as required. If the value is missing an error will occur.
Used `getOptionalString()` instead of `get()` to retrieve the value.
Ran tests and manual testing
---
=> fix: Resource locator type should be optional

docs/locating-resources.md, plugins/core/common/src/locator/resource-tagging-api-instance.ts, plugins/core/common/src/locator/resource-tagging-api-locator.test.ts, plugins/core/common/src/locator/resource-tagging-api-locator.ts
Closes #78 
The resource tagging locator mechanism should be able to work across multiple accounts and regions to facilitate setups where Resource Explorer or Config are not practical. This would allow resources to be looked up by tags across accounts and regions.
If no additional configuration is provided the locator will continue to behave as before.
Its now possible to optionally configure additional accounts and regions where the resource tagging API will be used to look up resources by tags. This looks like so:
```yaml
aws:
locator:
resourceTaggingApi:
accounts:
- '1111111111'
- '2222222222'
regions:
- us-east-1
- eu-west-2
```
Added unit test for multiple regions since this can be verified through existing mock patterns. Currently no unit tests for multiple accounts, this was …
=> feat: Support for multiple accounts and regions in resource tagging locator

plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.ts, plugins/codepipeline/backend/src/service/DefaultAwsCodePipelineService.ts, plugins/core/common/src/constants.ts, plugins/core/common/src/locator/aws-config-locator.ts, plugins/core/common/src/locator/resource-explorer-locator.ts, plugins/core/scaffolder-actions/package.json, plugins/core/scaffolder-actions/src/actions/cloudcontrol/create.ts, plugins/core/scaffolder-actions/src/actions/codecommit/publish.ts, plugins/core/scaffolder-actions/src/actions/eventbridge/eventbridge.ts, plugins/core/scaffolder-actions/src/actions/s3/cp.ts, plugins/ecs/backend/src/service/DefaultAmazonEcsService.ts, yarn.lock
N/A
The AWS SDK clients created are already adding custom user agent headers, but these headers are unique to each plugin. This makes it more difficult to create consistent filters to catch all AWS API calls when running Backstage in order to trace calls through services like CloudTrail.
Adds a string constant for a consistent user agent header and uses this throughout the various packages.
Existing unit tests
---
=> fix: Consistent user agent header for all AWS API calls

plugins/codepipeline/frontend/src/components/CodePipelineExecutions/CodePipelineExecutions.tsx, plugins/ecs/frontend/src/components/EcsServices/EcsServices.tsx
The placement of the title of the card for Amazon ECS Services and AWS CodePipeline was inconsistent with other Backstage components.
I move the title to the inside of the card for Amazon ECS Services and AWS CodePipeline. I also removed some box shadow and spacing caused due to the unused toolbar of the table inside the AWS ECS Services card to make it look less like a mix of individual components.
I tested the changes locally and took screenshots:
---
=> style: move the title to the inside of the card for Amazon ECS Services and AWS CodePipeline

plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.test.ts, plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.ts, plugins/codebuild/common/src/mocks/index.ts, plugins/codebuild/common/src/types.ts, plugins/codebuild/frontend/src/plugin.ts, plugins/codepipeline/backend/src/service/DefaultAwsCodePipelineService.ts, plugins/codepipeline/common/src/mocks/index.ts, plugins/codepipeline/common/src/types.ts, plugins/codepipeline/frontend/src/components/Router.tsx
Closes #7 
Some people already have a catalog that utilizes the annotations of the now deprecated `@aws/aws-codeservices-backend-plugin-for-backstage`. Updating to this version would require updating the `catalog-info.yaml` file of every entity, which can be a big undertaking depending on the amount of entities they have.
I added support for the previous annotations for CodePipeline and CodeBuild, while not recommending to use them anymore by leaving them out of the MissingAnnotationEmptyState.
I tested these changes locally and extended the current unit tests where applicable.
---
=> feat: Make CodePipeline and CodeBuild annotations backwards-compatible

plugins/ecs/backend/src/service/DefaultAmazonEcsService.test.ts, plugins/ecs/backend/src/service/DefaultAmazonEcsService.ts, plugins/ecs/frontend/src/components/EcsServices/EcsServices.tsx
Related to #140  
When the ECS API returns no tasks it should not display an error, just an empty list
Altered code path to gracefully handle no ECS tasks being returned
Added unit test for this scenario
---
=> fix: Handle case where no ECS tasks are returned

app-config.yaml, examples/entities.yaml, examples/org.yaml, plugins/codebuild/backend/src/plugin.ts, plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.ts, plugins/codebuild/backend/src/service/router.ts, plugins/codepipeline/backend/src/plugin.ts, plugins/codepipeline/backend/src/service/DefaultAwsCodePipelineService.ts, plugins/codepipeline/backend/src/service/router.ts, plugins/core/node/package.json, plugins/core/node/src/locator/aws-config-locator.ts, plugins/core/node/src/locator/resource-explorer-locator.ts, plugins/core/node/src/locator/resource-locator-factory.ts, plugins/core/node/src/locator/resource-tagging-api-instance.ts, plugins/core/node/src/locator/resource-tagging-api-locator.ts, plugins/cost-insights/backend/src/cache/CostInsightsCache.ts, plugins/cost-insights/backend/src/plugin.ts, plugins/cost-insights/backend/src/service/CostExplorerCostInsightsAwsService.ts, plugins/cost-insights/backend/src/service/router.ts, plugins/ecs/backend/src/plugin.ts, plugins/ecs/backend/src/service/DefaultAmazonEcsService.ts, plugins/ecs/backend/src/service/router.ts, yarn.lock
N/A
Allows other plugins to reference the APIs in the various backend plugins using dependency injection.
Declares a service reference for the API in each relevant backend plugin package.
Also migrates from winston to LoggerService.
Automated + manual testing
---
=> feat: Use serviceRefs for backend services

plugins/codepipeline/frontend/src/components/CodePipelineExecutions/CodePipelineExecutions.test.tsx, plugins/codepipeline/frontend/src/components/CodePipelineExecutions/CodePipelineExecutions.tsx
N/A
The logic to parse the revision summary isn't quite right and results in the column showing a JSON string in certain cases.
Changed the logic to always try to parse the revision summary string as JSON, and handle that appropriately. Otherwise treat it as a string.
Local testing
---
=> fix: Better handle parsing CodePipeline revision

plugins/core/catalog-config/src/providers/AwsConfigInfrastructureProvider.test.ts, plugins/core/catalog-config/src/providers/config.ts
N/A
Current if you try to use the Config catalog entity provider and try to set annotations that contains slashes you get an error:
```
Invalid config key 'aws.amazon.com/account-id'
```
Periods will also be parsed as nested fields due to the way the Backstage ConfigReader object [reads](https://github.com/backstage/backstage/blob/bc018aa540782987856f73280d6406bb591877d4/packages/config/src/reader.ts#L403) and validates configuration values.
This makes it impossible to implement EKS cluster catalog discovery with the provider since the annotations use periods and slashes in the names.
This change re-implements the function that loads configuration for field transforms to access fields on the underlying `JsonObject` instead of using the higher-level functions on ConfigReader.
Updated unit …
=> fix: Allow periods and slashes in transform field names

plugins/genai/agent-langgraph/README.md, plugins/genai/agent-langgraph/config.d.ts, plugins/genai/agent-langgraph/src/LangGraphReactAgentType.ts, plugins/genai/agent-langgraph/src/config/config.ts, plugins/genai/agent-langgraph/src/config/types.ts
Closes #316
Need to be able to support frameworks such as Ollama which provide an [OpenAI compatible interface](https://github.com/ollama/ollama/blob/main/docs/openai.md).
Therefore, it would make sense to be able to configure another `baseUrl` parameter for the endpoints than the default OpenAI endpoint (<https://api.openai.com/v1>).
I the needed code to add a new `langgraph.openai.baseUrl` parameter in the settings of the `aws-genai` plugin, that would look like this:
```yaml
genai:
agents:
general: # This matches the URL in the frontend
description: ...
prompt: ...
langgraph:
openai:
baseUrl: ${OPENAI_API_BASE_URL}
apiKey: ${OPENAI_API_KEY}
modelName: ${QUERY_MODEL_NAME}
```
Only tested it locally on my dev host at this point.
---
_By submitting this pull request, I confirm that my …
=> feat: Support OpenAI compatible APIs

plugins/genai/README.md, plugins/genai/docs/tools.md
There are some critical errors in the doc explaining how to use genai plugin tools:
- the parameter `tool` for the default general agent is mentioned instead of `tools`
- the name of the tool `backstageTechdocsSearch` has an error too. The right name of the provided tool is `backstageTechDocsSearch`
Fix the errors in the docs.
No but this issue impacts only the doc files.
---
=> docs: Fix reference to backstageTechDocsSearch

plugins/cost-insights/backend/src/service/CostExplorerCostInsightsAwsService.ts
Closes #323 
Parsing logic in upstream cost insights plugin expects dates of format yyyy-mm-dd not yyyy/mm/dd
Changes format per above
Manual testing
---
=> fix: Use correct date format for costs

plugins/cost-insights/README.md, plugins/cost-insights/backend/src/service/CostExplorerCostInsightsAwsService.ts
Closes #324.
Cost Insight backend had hard coded cost category of TAG which didn't make sense for most use cases. Instead make cost category key configurable using the same logic as Tag based filters.
Note that as this changes the way the category annotation is used it is a breaking change.
Restructures the cost explorer filter logic, so the same logic is logic is used for tags and categories, just with a change to the filter type.
Manually tested by repointing included examples and config to my own aws infra. All looks good
---
=> feat(cost-insights): Allow more flexible cost category selection

plugins/cost-insights/frontend/src/api/CostExplorerClient.ts
Currently only Groups in the default namespace are supported when opening the CostInsightsPage.    
If a Backstage instance uses non-default namespaces e.g. `group:team/a-team` then on opening the plugin still queries `group:default/a-team` which leads to page load failure.  This is as `group:a-team` will be interpreted as the default namespace
As the Catalog Query api  returns an Entity object, replaced the manual templating with the provided `stringifyEntityRef` function to create an ID.
---
=> fix: Correctly use namespaces groups for Cost Insights

plugins/genai/agent-langgraph/README.md, plugins/genai/agent-langgraph/config.d.ts, plugins/genai/agent-langgraph/src/LangGraphReactAgentType.ts, plugins/genai/agent-langgraph/src/config/config.ts, plugins/genai/agent-langgraph/src/config/types.ts
N/A
Puts a default cap on how many steps a single LangGraph agent can execute. This helps limit agents from exhibiting behavior that consumes a large number of tokens.
Added `recursionLimit` configuration parameter to shared LangGraph configuration. This means configuration can only be applied globally for now, per-agent configuration would require further changes.
Manual testing
---
=> feat: Added configurable langgraph recursion limit

plugins/genai/README.md, plugins/genai/backend/src/agent/Agent.ts, plugins/genai/backend/src/tools/invokeAgentTool.ts
N/A
Allow one agent to invoke another agent to architect simple multi-agent systems.
The tool code already existed, this change updates it so that the tool in the list should be prefixed with `agent:` instead of just the agent name.
Manual testing
---
=> feat: Agent communication

plugins/codebuild/backend/package.json, plugins/codebuild/backend/src/plugin.ts, plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.test.ts, plugins/codebuild/backend/src/service/DefaultAwsCodeBuildService.ts, plugins/codebuild/backend/src/service/router.test.ts, plugins/codebuild/backend/src/service/router.ts, plugins/codepipeline/backend/package.json, plugins/codepipeline/backend/src/plugin.ts, plugins/codepipeline/backend/src/service/DefaultAwsCodePipelineService.ts, plugins/codepipeline/backend/src/service/router.test.ts, plugins/codepipeline/backend/src/service/router.ts, plugins/core/scaffolder-actions/src/actions/s3/cp.ts, plugins/ecr/backend/package.json, plugins/ecr/backend/src/plugin.ts, plugins/ecr/backend/src/service/DefaultAmazonEcrService.ts, plugins/ecr/backend/src/service/router.ts, plugins/ecs/backend/package.json, plugins/ecs/backend/src/plugin.ts, plugins/ecs/backend/src/service/DefaultAmazonEcsService.test.ts, plugins/ecs/backend/src/service/DefaultAmazonEcsService.ts, plugins/ecs/backend/src/service/router.test.ts, plugins/ecs/backend/src/service/router.ts
N/A
Over time the various backend plugins in this repository have accumulated use of now deprecated APIs. Specifically:
1. Using the older `CatalogApi` and `catalogServiceRef`
2. Using the legacy auth adapter to retrieve user auth information
Mainly:
1. Replaced use of `CatalogApi` with `CatalogService`, which simplifies the services code since it doesn't have to generate a token for the catalog any more
2. Removed any reliance on legacy auth adapter, moving over to `HttpAuthService`
3. Migrated various unit test mocks
Unit tests and manual testing
---
=> feat: Remove reliance on deprecated backend APIs

plugins/core/scaffolder-actions/src/actions/cloudcontrol/create.ts
`ctx.logStream.write` is causing the following error:
```
2025-08-12T10:39:37.000Z Beginning step Create S3 Bucket
2025-08-12T10:39:37.000Z TypeError: Cannot read properties of undefined (reading 'write')
at Object.handler (/workspaces/backstage-app/backstage/node_modules/@aws/aws-core-plugin-for-backstage-scaffolder-actions/src/actions/cloudcontrol/create.ts:143:21)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async NunjucksWorkflowRunner.executeStep (/workspaces/backstage-app/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:373:9)
at async NunjucksWorkflowRunner.execute (/workspaces/backstage-app/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRun …
```
=> fix(core): use logger instead of logStream in scaffolder-actions

plugins/core/catalog-config/README.md, plugins/core/catalog-config/config.d.ts, plugins/core/catalog-config/src/providers/AwsConfigInfrastructureProvider.test.ts, plugins/core/catalog-config/src/providers/AwsConfigInfrastructureProvider.ts, plugins/core/catalog-config/src/providers/config.ts, plugins/core/catalog-config/src/providers/types.ts
Closes #385 #364
Currently the Config entity provider generates names using either the resource name from Config or if that is missing a hash of the ARN trimmed to maximum of 63 characters.
See the linked issues above for various problems with this approach.
Adds a flag `hashEntityNames` to the provider configuration schema that will trigger the provider to always generate entity names using a hash of the ARN. This retains the default behavior until the impact of this change can be better determined.
Unit tests
---
=> feat: Allow config provider to generate hashed entity names
